# Generated by Django 3.2.6 on 2021-08-22 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import roommates.managers
import roommates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_auto_20210821_2348'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('about_me', models.CharField(blank=True, max_length=500)),
                ('university', models.CharField(blank=True, max_length=80)),
                ('university_major', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, max_length=80)),
                ('is_lister', models.BooleanField(blank=True, default=False)),
                ('is_seeker', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city')),
                ('current_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.region')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', roommates.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('room_desc', models.CharField(max_length=1024)),
                ('room_type', models.CharField(choices=[('Unknown', 'Unknown'), ('Bedroom', 'Bedroom'), ('Shared Bedroom', 'Shared Bedroom'), ('Den', 'Den'), ('Living Room', 'Living Room'), ('Shared Living Room', 'Shared Living Room'), ('Sunroom', 'Sunroom'), ('Closet', 'Closet')], default='Unknown', max_length=18)),
                ('is_furnished', models.BooleanField()),
                ('is_air_conditioned', models.BooleanField()),
                ('is_laundry_ensuite', models.BooleanField()),
                ('number_of_bathrooms', models.PositiveIntegerField()),
                ('number_of_residents', models.PositiveIntegerField()),
                ('rent_per_month', models.DecimalField(decimal_places=2, max_digits=7)),
                ('length_of_lease', models.PositiveIntegerField()),
                ('extra_expenses_per_month', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address1', models.CharField(max_length=1024)),
                ('address2', models.CharField(blank=True, max_length=10)),
                ('postal_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=32)),
                ('province', models.CharField(max_length=25)),
                ('earliest_move_in_date', models.DateField()),
                ('listing_expiry_date', models.DateField(default=roommates.models.default_expiry_date)),
                ('listing_visits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='default.jpeg', upload_to=roommates.models.upload_user_profile_image)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=roommates.models.upload_gallery_image)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=roommates.models.upload_gallery_image)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.listing')),
            ],
        ),
    ]
