# Generated by Django 3.2.6 on 2021-08-22 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0002_auto_20210822_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a postal code in the following format XXX XXX', regex='^(?!.*[DFIOQU])[A-VXY][0-9][A-Z]●?[0-9][A-Z][0-9]$')]),
        ),
    ]
