# Generated by Django 3.2.6 on 2021-09-26 21:34

from django.db import migrations, models
import roommates.validators.user_validators


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0002_auto_20210925_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(help_text='Date of birth of user. Must be 18 years old or older', validators=[roommates.validators.user_validators.validate_user_age], verbose_name='Date Of Birth'),
        ),
    ]
