# Generated by Django 3.2.6 on 2021-08-03 20:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0002_listing_listing_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_title',
            field=models.CharField(default=datetime.datetime(2021, 8, 3, 20, 1, 8, 526293, tzinfo=utc), max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
