# Generated by Django 3.2.6 on 2021-08-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0003_alter_listing_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='current_province',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_province',
        ),
    ]
