# Generated by Django 3.2.6 on 2021-08-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0004_auto_20210822_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_major',
            field=models.CharField(max_length=50),
        ),
    ]
