# Generated by Django 3.2.6 on 2021-10-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0004_alter_user_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image_name',
            field=models.CharField(blank=True, help_text='Name of image', max_length=36, null=True, unique=True, verbose_name='Image Name'),
        ),
    ]
