# Generated by Django 3.2.6 on 2021-08-22 19:56

from django.db import migrations, models
import roommates.models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0006_auto_20210822_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/users/profile/default.jpeg', upload_to=roommates.models.upload_user_profile_image, verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='UserProfileImage',
        ),
    ]
