# Generated by Django 3.2.6 on 2021-08-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import roommates.models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0007_auto_20210822_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='images/users/profile/default.jpeg', upload_to=roommates.models.upload_user_profile_image, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
