# Generated by Django 3.2.6 on 2021-08-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0008_auto_20210804_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('UNKN', 'Unknown'), ('BDR', 'Bedroom'), ('SBDR', 'Shared_Bedroom'), ('DEN', 'Den'), ('LR', 'Living_room'), ('SLR', 'Shared_Living_Room'), ('SR', 'Sunroom'), ('CLO', 'Closet')], default='UNKN', max_length=4),
        ),
    ]
