# Generated by Django 3.2.6 on 2021-08-23 01:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import roommates.models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0009_auto_20210822_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userimagegallery',
            options={'verbose_name': 'UserImageGallery', 'verbose_name_plural': 'UserImageGallerys'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_seeker',
        ),
        migrations.AlterField(
            model_name='listing',
            name='address1',
            field=models.CharField(help_text='Address of rental property without unit/apt/floor number.', max_length=1024, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address2',
            field=models.CharField(blank=True, help_text='Unit/apt/floor number of rental property.', max_length=10, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(help_text='Canadian city of rental property.', max_length=32, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='Indicates when listing instance was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='earliest_move_in_date',
            field=models.DateField(help_text='Specifies earlist move in date for rental property.', verbose_name='Earliest Move In Date'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='extra_expenses_per_month',
            field=models.DecimalField(decimal_places=2, help_text='Extra expenses per month between $0.00 to $9,999.99.', max_digits=6, verbose_name='Extra Expenses Per Month'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_air_conditioned',
            field=models.BooleanField(help_text='Indicates whether listed room has air conditioning.', verbose_name='Is Air Conditioned'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_furnished',
            field=models.BooleanField(help_text='Indicates whether listed room is furnished.', verbose_name='Is Furnished'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_laundry_ensuite',
            field=models.BooleanField(help_text='Indicates whether listed room has ensuite laundry.', verbose_name='Is Laundry Ensuite'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='length_of_lease',
            field=models.PositiveIntegerField(help_text='Specifies length of lease between 1 to 24 months.', validators=[roommates.models.validate_lease_length], verbose_name='Length of Lease'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_expiry_date',
            field=models.DateField(default=roommates.models.default_expiry_date, help_text='Specifies expiry date of listing. Default 30 days from lisitng.', verbose_name='Listing Expiry Date'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_title',
            field=models.CharField(help_text='Title of the rental listing.', max_length=70, verbose_name='Listing Title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_visits',
            field=models.PositiveIntegerField(default=0, help_text='Specifies number of visits for this listing.', verbose_name='Listing Visits'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(help_text='Indicates number of bathrooms for rental property.', validators=[roommates.models.validate_number_bathrooms], verbose_name='Number Of Bathrooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='number_of_residents',
            field=models.PositiveIntegerField(help_text='Indicates number of current tenants in rental property.', validators=[roommates.models.validate_number_residents], verbose_name='Number Of Residents'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='postal_code',
            field=models.CharField(help_text='Canadian postal code of rental property.', max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a postal code in the following format XXX XXX', regex='^(?!.*[DFIOQU])[A-VXY][0-9][A-Z]●?[0-9][A-Z][0-9]$')], verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='poster',
            field=models.OneToOneField(help_text='The associated user the listing belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='province',
            field=models.CharField(help_text='Canadian province of rental property.', max_length=25, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rent_per_month',
            field=models.DecimalField(decimal_places=2, help_text='Rent per month between $0.00 to $99,999.99.', max_digits=7, verbose_name='Rent Per Month'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='room_desc',
            field=models.CharField(help_text='A description of the room being listed.', max_length=1024, verbose_name='Room Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Bedroom', 'Bedroom'), ('Shared Bedroom', 'Shared Bedroom'), ('Den', 'Den'), ('Living Room', 'Living Room'), ('Shared Living Room', 'Shared Living Room'), ('Sunroom', 'Sunroom'), ('Closet', 'Closet')], default='Unknown', help_text='Specifies room type from set of room choices.', max_length=18, verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(help_text='Slug to generate a unique url for the listing.', max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Indicates when listing instance was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='listingimagegallery',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='Indicates when listing image instance was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='listingimagegallery',
            name='image',
            field=models.ImageField(default='images/listings/default.jpeg', upload_to=roommates.models.upload_gallery_image, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='listingimagegallery',
            name='listing',
            field=models.ForeignKey(help_text='Image belongs to associated listing', on_delete=django.db.models.deletion.CASCADE, to='roommates.listing', verbose_name='Listing'),
        ),
        migrations.AlterField(
            model_name='listingimagegallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Indicates when listing image instance was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(help_text='Short description about the user.', max_length=500, verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(help_text='Canadian city the user currently resides.', max_length=32, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='Indicates when user instance was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(help_text='Date of birth of user. Must be 18 years old or older', verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email of user. Must be unique.', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='First name of user.', max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_lister',
            field=models.BooleanField(blank=True, default=False, help_text='Specifies if user has a listing. Set when listing created.', verbose_name='Is Lister'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Last name of user.', max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, help_text='Profession of user. Can be empty.', max_length=80, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/users/profile/default.jpeg', help_text='Profile picture of user.', upload_to=roommates.models.upload_user_profile_image, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(help_text='Canadian province the user currently resides.', max_length=25, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, help_text='University that user goes to. Can be empty.', max_length=80, verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_major',
            field=models.CharField(blank=True, help_text='University major of user. Can be empty.', max_length=50, verbose_name='University Major'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Indicates when user instance was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userimagegallery',
            name='created_at',
            field=models.DateTimeField(auto_now=True, help_text='Indicates when user image instace was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='userimagegallery',
            name='image',
            field=models.ImageField(default='images/users/gallery/default.jpeg', help_text='Image instance in filesystem', upload_to=roommates.models.upload_gallery_image, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='userimagegallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Indicates when user image instace was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='userimagegallery',
            name='user',
            field=models.ForeignKey(help_text='Image belongs to associated user.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
