# Generated by Django 3.2.6 on 2021-08-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0009_listing_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('UNKN', 'Unknown'), ('BDR', 'Bedroom'), ('SBDR', 'Shared Bedroom'), ('DEN', 'Den'), ('LR', 'Living Room'), ('SLR', 'Shared Living Room'), ('SR', 'Sunroom'), ('CLO', 'Closet')], default='UNKN', max_length=4),
        ),
    ]
