# Generated by Django 3.2.6 on 2021-08-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0010_auto_20210823_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rent_per_month',
            field=models.DecimalField(decimal_places=2, help_text='Rent per month between $0.00 to $9,999.99.', max_digits=6, verbose_name='Rent Per Month'),
        ),
    ]
