# Generated by Django 3.2.6 on 2021-08-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
    ]
