# Generated by Django 3.2.6 on 2021-08-05 03:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0012_alter_listing_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='earliest_move_in_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 5, 3, 4, 4, 663555, tzinfo=utc)),
        ),
    ]
