# Generated by Django 3.2.6 on 2021-08-24 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profanity.validators
import roommates.models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0013_alter_listing_extra_expenses_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address2',
            field=models.CharField(blank=True, help_text='Unit/apt/floor number of rental property.', max_length=10, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_title',
            field=models.CharField(help_text='Title of the rental listing.', max_length=70, validators=[profanity.validators.validate_is_profane], verbose_name='Listing Title'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='room_desc',
            field=models.CharField(help_text='A description of the room being listed.', max_length=1024, validators=[profanity.validators.validate_is_profane], verbose_name='Room Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(help_text='Short description about the user.', max_length=500, validators=[profanity.validators.validate_is_profane], verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='First name of user.', max_length=150, validators=[profanity.validators.validate_is_profane], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_lister',
            field=models.BooleanField(blank=True, default=False, help_text='Specifies if user has a listing. Set when listing created.', null=True, verbose_name='Is Lister'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Last name of user.', max_length=150, validators=[profanity.validators.validate_is_profane], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, help_text='Profession of user. Can be empty.', max_length=80, null=True, validators=[profanity.validators.validate_is_profane], verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/users/profile/default.jpeg', help_text='Profile picture of user. If none choses default displayed.', null=True, upload_to=roommates.models.upload_user_profile_image, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, help_text='University that user goes to. Can be empty.', max_length=80, null=True, verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_major',
            field=models.CharField(blank=True, help_text='University major of user. Can be empty.', max_length=50, null=True, validators=[profanity.validators.validate_is_profane], verbose_name='University Major'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_listing_gallery', models.BooleanField(help_text='Indicates if this gallery belongs to a listing.', verbose_name='Is Listing Gallery')),
                ('is_user_gallery', models.BooleanField(help_text='Indicates if this gallery belongs to a user.', verbose_name='Is User Gallery')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Indicates when listing instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Indicates when listing instance was last updated.', verbose_name='Updated At')),
                ('listing', models.ForeignKey(blank=True, help_text='Gallery belongs to associated user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='roommates.listing', verbose_name='User')),
                ('user', models.ForeignKey(blank=True, help_text='Gallery belongs to associated user.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
