# Generated by Django 3.2.6 on 2021-08-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0014_alter_listing_earliest_move_in_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='latest_move_in_date',
        ),
        migrations.AlterField(
            model_name='listing',
            name='earliest_move_in_date',
            field=models.DateField(),
        ),
    ]
