# Generated by Django 3.2.6 on 2021-08-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0015_auto_20210824_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallerys'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
    ]
