# Generated by Django 3.2.6 on 2021-08-09 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import roommates.models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0016_auto_20210805_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_city',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_province',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_major',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='default.jpeg', upload_to=roommates.models.upload_user_profile_image)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
