# Generated by Django 3.2.6 on 2021-08-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0018_auto_20210809_0143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingImage',
            new_name='ListingImageGallery',
        ),
        migrations.RenameModel(
            old_name='UserImage',
            new_name='UserImageGallery',
        ),
        migrations.AddField(
            model_name='userprofileimage',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofileimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
