# Generated by Django 3.2.6 on 2021-08-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0020_alter_listing_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_lister',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_seeker',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
