# Generated by Django 3.2.6 on 2021-08-12 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0022_alter_user_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique_for_date='created_at'),
            preserve_default=False,
        ),
    ]
