# Generated by Django 3.2.6 on 2021-08-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0024_alter_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
