# Generated by Django 3.2.6 on 2021-08-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0026_listing_length_of_lease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
