# Generated by Django 3.2.6 on 2021-08-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0027_alter_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_air_conditioned',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='is_laundry_ensuite',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
