# Generated by Django 3.2.6 on 2021-08-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0005_remove_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='additional_expenses_per_month',
            new_name='extra_expenses_per_month',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='number_current_residents',
            new_name='number_of_residents',
        ),
    ]
