# Generated by Django 3.2.6 on 2021-08-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0015_auto_20210805_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
