# Generated by Django 3.2.6 on 2021-08-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0019_auto_20210809_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Bedroom', 'Bedroom'), ('Shared Bedroom', 'Shared Bedroom'), ('Den', 'Den'), ('Living Room', 'Living Room'), ('Shared Living Room', 'Shared Living Room'), ('Sunroom', 'Sunroom'), ('Closet', 'Closet')], default='Unknown', max_length=18),
        ),
    ]
