# Generated by Django 3.2.6 on 2021-08-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0021_auto_20210810_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
