# Generated by Django 3.2.6 on 2021-08-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0025_alter_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='length_of_lease',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
